#!/usr/bin/env python3
"""
Register a Lighter API key for the bot. ONE TIME, and it needs your L1 wallet.

    set ETH_PRIVATE_KEY=0x...            the key that owns the account's l1_address
    python keeper/register-api-key.py    generate, register at index 4, print the key once

    python keeper/register-api-key.py --dry     generate and show, register nothing

WHY THIS IS A SCRIPT YOU RUN RATHER THAN SOMETHING AUTOMATED
Registering touches the chain with your L1 key — the one that actually owns the account and its
money. It happens once, it should be watched, and the key should never be anywhere but your own
shell. Nothing here writes a key to disk, logs one, or sends one anywhere.

WHY INDEX 4 AND NOT 0
Lighter reserves 0-3 for its own desktop and mobile interfaces. A key you generated by logging into
the web app lives at 0, and pointing a bot at that slot means two signers sharing one nonce sequence
— which works right up until you happen to have Lighter open in a tab while the loop is running.
Bots use 4 and above.

AFTERWARDS
The private half is printed ONCE and never stored. Put it in your environment:

    set LIGHTER_API_KEY=<the private key printed below>

and check keeper/config.json has lighter.apiKeyIndex matching the index used here.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

HOST = "https://api.rh.lighter.xyz"
# THE SIGNING CHAIN ID IS NOT THE SETTLEMENT CHAIN ID, and getting that wrong is indistinguishable
# from a bad key: every signature verifies against the wrong domain and comes back
# `21120 invalid signature`, whatever the key is and whatever is in the order.
#
#   4663    Robinhood Chain, the L1 the ZkLighter deposit contract lives on. Used by keeper/harvest.js.
#   466324  Lighter's own L2 behind api.rh.lighter.xyz. Everything SIGNED for the exchange uses this.
CHAIN_ID = 466324
SETTLEMENT_CHAIN_ID = 4663      # where deposits land; never used for signing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--index", type=int, default=4, help="api key slot; 0-3 are reserved by Lighter")
    ap.add_argument("--account", type=int, default=None, help="defaults to keeper/config.json")
    ap.add_argument("--dry", action="store_true", help="generate and show, register nothing")
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    cfg = json.load(open(os.path.join(here, "config.json"), encoding="utf-8"))
    account = args.account if args.account is not None else int(cfg["lighter"]["accountIndex"])
    if account <= 0:
        sys.exit("lighter.accountIndex is not set in keeper/config.json")
    if args.index < 4:
        print(f"! index {args.index} is reserved by Lighter for its own apps. Use 4 or above.\n")

    try:
        import lighter
    except ImportError:
        sys.exit("pip install lighter-sdk==1.1.2")

    # 1. a fresh Lighter-native keypair. NOT an EVM key — different curve, different purpose.
    priv, pub, err = lighter.create_api_key()
    if err:
        sys.exit(f"create_api_key failed: {err}")
    print(f"account       {account}")
    print(f"slot          {args.index}")
    print(f"public key    {pub}")

    if args.dry:
        print("\n--dry: nothing registered. Re-run without --dry to write it on chain.")
        print("(the private half is not shown in a dry run, because it would be a key you cannot use)")
        return

    eth = (os.environ.get("ETH_PRIVATE_KEY") or "").strip()
    if not eth:
        sys.exit("\nset ETH_PRIVATE_KEY to the L1 key that owns the account, then run again.\n"
                 "It is read from the environment, used once, and never written anywhere.")

    # 2. register the PUBLIC half against the account. Signed with the L1 key, on chain, once.
    import asyncio

    async def go():
        signer = lighter.SignerClient(
            url=HOST, account_index=account,
            api_private_keys={args.index: priv}, chain_id=CHAIN_ID,
        )
        try:
            res = await signer.change_api_key(
                eth_private_key=eth if eth.startswith("0x") else "0x" + eth,
                new_pubkey=pub,
                api_key_index=args.index,
            )
            # the SDK returns a tuple whose LAST element is the error, and never raises it
            if isinstance(res, tuple) and res[-1]:
                sys.exit(f"change_api_key failed: {res[-1]}")
            print("\nregistered on chain.")
        finally:
            close = getattr(signer, "close", None)
            if close:
                r = close()
                if hasattr(r, "__await__"):
                    await r

    asyncio.run(go())

    print("\n" + "=" * 68)
    print("THE PRIVATE KEY IS SHOWN ONCE AND STORED NOWHERE. Copy it now:\n")
    print(f"    set LIGHTER_API_KEY={priv}\n")
    print(f"and confirm keeper/config.json has lighter.apiKeyIndex = {args.index}")
    print("=" * 68)
    print("\nIt can take a few seconds to land. Check it with:")
    print(f"  curl \"{HOST}/api/v1/apikeys?account_index={account}&api_key_index={args.index}\"")


if __name__ == "__main__":
    main()
